### ISSUE TITLE
Format of files for building the dataset

### ISSUE THREAD

**Issue by kartikeya-badola** [thunlp/AMNRE#9]
Thank you authors for their work. Would it be possible for the authors to share the format of the text files which are processed by the init.py code in CNN/RNN folders? Baidu is not available in some countries. 

It would be very helpful if the authors could just provide an example of an instance from all of the files used to build the dataset.

**Comment by Bakser** [comment]
Hi. Thanks for your interest in our work. I have changed the data download source to Tsinghua Cloud. Can you try if you can download it now?

**Comment by kartikeya-badola** [comment]
Its working now! Thank you so much. I had one more concern, the dataloader seems to be hardcoded for only two languages. How can we extend your work for multilingual datasets?

**Comment by Bakser** [comment]
Yes it is because this code is only for experiments on English and Chinese. If you want to modify it for more languages, I suggest to change the variables to arrays and use the index to indicate the language. For example, change wordsEn and wordsZh to words[0] and words[1], and the trainer.py and models.py should be modified in a similar way.
